version: '3.1'
services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
  localS3:
    image: luofuxiang/local-s3:native-1.12.1
    ports:
      - "8081:80"

  app:
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_PROFILES_ACTIVE=local
      - AWS_ACCESS_KEY_ID=LOCAL
      - AWS_SECRET_ACCESS_KEY=LOCAL
      - LOCAL_S3_HOST=localS3
      - LOCAL_S3_PORT=80
    image: mateuszsek/backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - localS3
